### ISSUE TITLE
Simplify CSS code for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [HeartSoSavage/prj-rev-bwfs-dasmoto#6]
It is a good idea to try and simplify the CSS code as much as possible to make the code cleaner and to remove repetitive code. For instance, the font-family and font-weight property values are shared by multiple elements. You can apply it to all the elements building upon what you have so far,

```css
html {
  font-family: Helvetica;
  font-weight: bold;
}
```

then remove the lines where the individual selectors have the same properties, which were lines 7, 32, and 34 before this change.
